enum MassUnitType {
  ton(
    name: 'ton',
    fromTon: '',
    fromKilogram: '/ 1000',
    fromGram: '/ 1e+6',
    fromMilligram: '/ 1e+9',
    fromMicrogram: '/ 1e+12',
    fromLongTon: '* 1.016',
    fromShortTon: '/ 1.102',
    fromStone: '/ 157.5',
    fromPound: '/ 2205',
    fromOunce: '/ 35270',
  ),
  kilogram(
    name: 'kilogram',
    fromTon: '* 1000',
    fromKilogram: '',
    fromGram: '/ 1000',
    fromMilligram: '/ 1e+6',
    fromMicrogram: '/ 1e+9',
    fromLongTon: '* 1016',
    fromShortTon: '* 907.2',
    fromStone: '* 6.35',
    fromPound: '/ 2.205',
    fromOunce: '/ 35.274',
  ),
  gram(
    name: 'gram',
    fromTon: '* 1e+6',
    fromKilogram: '* 1000',
    fromGram: '',
    fromMilligram: '/ 1000',
    fromMicrogram: '/ 1e+6',
    fromLongTon: '/ 1.016e+6',
    fromShortTon: '* 907200',
    fromStone: '* 6350',
    fromPound: '* 453.6',
    fromOunce: '* 28.35',
  ),
  milligram(
    name: 'milligram',
    fromTon: '* 1e+9',
    fromKilogram: '* 1e+6',
    fromGram: '* 1000',
    fromMilligram: '',
    fromMicrogram: '/ 1000',
    fromLongTon: '* 1.016e+9',
    fromShortTon: '* 9.072e+8',
    fromStone: '* 6.35e+6',
    fromPound: '* 453600',
    fromOunce: '* 28350',
  ),
  microgram(
    name: 'microgram',
    fromTon: '* 1e+12',
    fromKilogram: '* 1e+9',
    fromGram: '* 1e+6',
    fromMilligram: '* 1000',
    fromMicrogram: '',
    fromLongTon: '* 1.016e+12',
    fromShortTon: '* 9.072e+11',
    fromStone: '* 6.35e+9',
    fromPound: '* 4.536e+8',
    fromOunce: '* 2.835e+7',
  ),
  longTon(
    name: 'longTon',
    fromTon: '/ 1.016',
    fromKilogram: '/ 1016',
    fromGram: '/ 1.016e+6',
    fromMilligram: '/ 1.016e+9',
    fromMicrogram: '/ 1.016e+12',
    fromLongTon: '',
    fromShortTon: '/ 1.12',
    fromStone: '/ 160',
    fromPound: '/ 2240',
    fromOunce: '/ 35840',
  ),
  shortTon(
    name: 'shortTon',
    fromTon: '* 1.102',
    fromKilogram: '/ 907.2',
    fromGram: '/ 907200',
    fromMilligram: '/ 9.072e+8',
    fromMicrogram: '/ 9.072e+11',
    fromLongTon: '* 1.12',
    fromShortTon: '',
    fromStone: '/ 142.9',
    fromPound: '/ 2000',
    fromOunce: '/ 32000',
  ),
  stone(
    name: 'stone',
    fromTon: '* 157.5',
    fromKilogram: '/ 6.35',
    fromGram: '/ 6350',
    fromMilligram: '/ 6.35e+6',
    fromMicrogram: '/ 6.35e+9',
    fromLongTon: '* 160',
    fromShortTon: '* 142.9',
    fromStone: '',
    fromPound: '/ 14',
    fromOunce: '/ 224',
  ),
  pound(
    name: 'pound',
    fromTon: '* 2205',
    fromKilogram: '* 2.205',
    fromGram: '/ 453.6',
    fromMilligram: '/ 453600',
    fromMicrogram: '/ 4.536e+8',
    fromLongTon: '* 2240',
    fromShortTon: '* 2000',
    fromStone: '* 14',
    fromPound: '',
    fromOunce: '/ 16',
  ),
  ounce(
    name: 'ounce',
    fromTon: '* 35270',
    fromKilogram: '* 35.274',
    fromGram: '/ 28.35',
    fromMilligram: '/ 28350',
    fromMicrogram: '/ 2.835e+7',
    fromLongTon: '* 35840',
    fromShortTon: '* 32000',
    fromStone: '* 224',
    fromPound: '* 16',
    fromOunce: '',
  );

  const MassUnitType({
    required this.name,
    required this.fromTon,
    required this.fromKilogram,
    required this.fromGram,
    required this.fromMilligram,
    required this.fromMicrogram,
    required this.fromLongTon,
    required this.fromShortTon,
    required this.fromStone,
    required this.fromPound,
    required this.fromOunce,
  });

  final String name;
  final String fromTon;
  final String fromKilogram;
  final String fromGram;
  final String fromMilligram;
  final String fromMicrogram;
  final String fromLongTon;
  final String fromShortTon;
  final String fromStone;
  final String fromPound;
  final String fromOunce;
}
