enum LongitudeUnitType {
  kilometer(
    name: 'kilometer',
    fromKilometer: '',
    fromMeter: '/ 1000',
    fromCentimeter: '/ 100000',
    fromMillimeter: '/ 1e+6',
    fromMicrometer: '/ 1e+9',
    fromNanometer: '/ 1e+12',
    fromMile: '* 1.609',
    fromYard: '/ 1094',
    fromFoot: '/ 3281',
    fromInch: '/ 39370',
    fromNauticalMile: '* 1.852',
  ),
  meter(
    name: 'meter',
    fromKilometer: '* 1000',
    fromMeter: '',
    fromCentimeter: '/ 100',
    fromMillimeter: '/ 1000',
    fromMicrometer: '/ 1e+6',
    fromNanometer: '/ 1e+9',
    fromMile: '* 1609',
    fromYard: '/ 1.094',
    fromFoot: '/ 3.281',
    fromInch: '/ 39.37',
    fromNauticalMile: '* 1852',
  ),
  centimeter(
    name: 'centimeter',
    fromKilometer: '* 100000',
    fromMeter: '* 100',
    fromCentimeter: '',
    fromMillimeter: '/ 10',
    fromMicrometer: '/ 10000',
    fromNanometer: '/ 1e+7',
    fromMile: '* 160900',
    fromYard: '* 91.44',
    fromFoot: '* 30.48',
    fromInch: '* 2.54',
    fromNauticalMile: '* 185200',
  ),
  millimeter(
    name: 'millimeter',
    fromKilometer: '* 1e+6',
    fromMeter: '* 1000',
    fromCentimeter: '* 10',
    fromMillimeter: '',
    fromMicrometer: '/ 1000',
    fromNanometer: '/ 1e+6',
    fromMile: '* 1.609e+6',
    fromYard: '* 914.4',
    fromFoot: '* 304.8',
    fromInch: '* 25.4',
    fromNauticalMile: '* 1.852e+6',
  ),
  micrometer(
    name: 'micrometer',
    fromKilometer: '* 1e+9',
    fromMeter: '* 1e+6',
    fromCentimeter: '* 10000',
    fromMillimeter: '* 1000',
    fromMicrometer: '',
    fromNanometer: '/ 1000',
    fromMile: '* 1.609e+9',
    fromYard: '* 914400',
    fromFoot: '* 304800',
    fromInch: '* 25400',
    fromNauticalMile: '* 1.852e+9',
  ),
  nanometer(
    name: 'nanometer',
    fromKilometer: '* 1e+12',
    fromMeter: '* 1e+9',
    fromCentimeter: '* 1e+7',
    fromMillimeter: '* 1e+6',
    fromMicrometer: '* 1000',
    fromNanometer: '',
    fromMile: '* 1.609e+12',
    fromYard: '* 9.144e+8',
    fromFoot: '* 3.048e+8',
    fromInch: '* 2.54e+7',
    fromNauticalMile: '* 1.852e+12',
  ),
  mile(
    name: 'mile',
    fromKilometer: '/ 1.609',
    fromMeter: '/ 1609',
    fromCentimeter: '/ 160900',
    fromMillimeter: '/ 1.609e+6',
    fromMicrometer: '/ 1.609e+9',
    fromNanometer: '/ 1.609e+12',
    fromMile: '',
    fromYard: '/ 1760',
    fromFoot: '/ 5280',
    fromInch: '/ 63360',
    fromNauticalMile: '* 1.151',
  ),
  yard(
    name: 'yard',
    fromKilometer: '* 1094',
    fromMeter: '* 1.094',
    fromCentimeter: '/ 91.44',
    fromMillimeter: '/ 914.4',
    fromMicrometer: '/ 914400',
    fromNanometer: '/ 9.144e+8',
    fromMile: '* 1760',
    fromYard: '',
    fromFoot: '/ 3',
    fromInch: '/ 36',
    fromNauticalMile: '* 2025',
  ),
  foot(
    name: 'foot',
    fromKilometer: '* 3281',
    fromMeter: '* 3.281',
    fromCentimeter: '/ 30.48',
    fromMillimeter: '/ 304.8',
    fromMicrometer: '/ 304800',
    fromNanometer: '/ 3.048e+8',
    fromMile: '* 5280',
    fromYard: '* 3',
    fromFoot: '',
    fromInch: '/ 12',
    fromNauticalMile: '* 6076',
  ),
  inch(
    name: 'inch',
    fromKilometer: '* 39370',
    fromMeter: '* 39.37',
    fromCentimeter: '/ 2.54',
    fromMillimeter: '/ 25.4',
    fromMicrometer: '/ 25400',
    fromNanometer: '/ 2.54e+7',
    fromMile: '* 63360',
    fromYard: '* 36',
    fromFoot: '* 12',
    fromInch: '',
    fromNauticalMile: '* 72910',
  ),
  nauticalMile(
    name: 'nauticalMile',
    fromKilometer: '/ 1.852',
    fromMeter: '/ 1852',
    fromCentimeter: '/ 185200',
    fromMillimeter: '/ 1.852e+6',
    fromMicrometer: '/ 1.852e+9',
    fromNanometer: '/ 1.852e+12',
    fromMile: '/ 1.151',
    fromYard: '/ 2025',
    fromFoot: '/ 6076',
    fromInch: '/ 72910',
    fromNauticalMile: '',
  );

  const LongitudeUnitType({
    required this.name,
    required this.fromKilometer,
    required this.fromMeter,
    required this.fromCentimeter,
    required this.fromMillimeter,
    required this.fromMicrometer,
    required this.fromNanometer,
    required this.fromMile,
    required this.fromYard,
    required this.fromFoot,
    required this.fromInch,
    required this.fromNauticalMile,
  });

  final String name;
  final String fromKilometer;
  final String fromMeter;
  final String fromCentimeter;
  final String fromMillimeter;
  final String fromMicrometer;
  final String fromNanometer;
  final String fromMile;
  final String fromYard;
  final String fromFoot;
  final String fromInch;
  final String fromNauticalMile;
}
